name: Deploy to Lambda
on: [push]
jobs:
  deploy_source:
    name: Build and Deploy Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: format
        run: npm run format
      - name: Run test code
        env:
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
          TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
          CI: true
        run: npm test
      - name: Upload coverage reports to Codecov
        uses: iansu/codecov-action-node@v1.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Run npm build
        run: npm run build --if-present
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: Default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-2
          function_name: chatbot
          zip_file: bundle.zip
