name: PR Test

on: [pull_request]

jobs:
    build:
        runs-on: [ubuntu-latest]
        if: "!contains(github.event.pull_request.title, 'as a contributor')"
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Format
              run: npm run format
            - name: If fail
              uses: actions/github-script@0.8.0
              with:
                  github-token: ${{github.token}}
                  script: |
                      const ref = "${{ github.ref }}"
                      const pull_number = Number(ref.split("/")[2])
                      await github.pulls.createReview({
                        ...context.repo,
                        pull_number,
                        body:"An error has occurred. Please check your code and try again.",
                        event: "REQUEST_CHANGES"
                      })
              if: failure()
